package model;

public enum SprzetStatus {
    W_DRODZE_DO_OPERATORA,
    W_MAGAZYNIE,
    CZEKA_NA_WYDANIE_KLIENTOWI,
    CZEKA_NA_WYDANIE_MAGAZYNIEROWI,
    W_DRODZE_DO_MAGAZYNU,
    W_NAPRAWIE,
    WYPOZYCZONY
}
