@startuml DataBase	
    
    class "BazaDanych" as BAD {
		- uprawnienia : Map<int, Uprawnienie>
		- kategorie : Set<Kategoria>
		- etykiety : Set<Etykieta>
		- marki : Set<Marka>
		- sprzety : Set<Sprzety>
		- wypozycenia : Set<Wypozycenie>
		- uzytkownicy : Set<Uzytkownik>
		- platnosci : Set<Platnosc>
		- wnioski : Set<Wniosek>
		- zlecenia : Set<Zlecenie>
		+ gettery(ale takie specjalne)() : ...
	}

	enum "Uprawnienie" as UPR {
		ADMIN,
		KLIENT,
		MAGAZYNIER,
		PRACOWNIK_BIURA
	}

	class "Kategoria" as KAT {
		- id : int
		- nazwa : String
		- etykiety : Set<Etykieta>
		- cenaZaDzien : double
		- cenaZaWyporzyczenie : double
		- cenaZaOpoznienie : double
		- cenaZaOpoznienieZaDzien : double
		+ Kategoia(String)
		+ ustawCeneZaDzien(double) : void
		+ ustawCeneZaWyporzyczenie(double) : void
		+ ustawCeneZaOpoznienie(double) : void
		+ ustawCeneZaOpoznienieZaDzien(double) : void
		+ gettery() : ...
		+ settery(bez etykiety i id)(...) : void 
	}

	class "Etykieta" as ETY {
		- id : int
		- nazwa : String
		- marka : Marka
		- opis : String
		- kategoria : Kategoria
		- sprzety : Set<Sprzet>
		- cenaZaDzien : double
		- cenaZaWyporzyczenie : double 
		- cenaZaOpoznienie : double
		- cenaZaOpoznienieZaDzien : double
		+ Etykieta(String, Marka, String, Kategoria)
		+ ustawCeneZaDzien(double) : void
		+ ustawCeneZaWyporzyczenie(double) : void
		+ ustawCeneZaOpoznienie(double) : void
		+ ustawCeneZaOpoznienieZaDzien(double) : void
		+ gettery() : ...
		+ settery(bez sprzety i id)(...) : void 
	}

	class "Marka" as MAR {
		- ind : int
		- nazwa : String
		- etykiety : Set<Etykieta>
		+ Marka(String)
		+ wezNazwa() : String
		+ ustawNazwa(String) : void
	}

	class "Sprzet" as SPR {
		- id : int
		- dniEksploatacji : int
		- etykieta : Etykieta
		- status : SprzetStatus
		- wypozycenie : Optional<Wypozycenie>
		- rezerwacje : Set<Wypozycenie>
		- {static} domyslnaCenaZaDzien : double
		- {static} domyslnaCenaZaWyporzyczenie : double
		- {static} domyslnaCenaZaOpoznienie : double
		- {static} domyslnaCenaZaOpoznienieZaDzien : double
		+ Sprzet(Etykieta)
		+ gettery() : ...
		+ settery(bez id, dniEksploatacji, i rezerwacje)(...) : void
		+ eksploatuj(int);
	}

	class "Wypozycenie" as WYP {
		- id : int
		- start : Date
		- end : Date
		- wplacono : double
		- doZaplaty : double
		- sprzet : Sprzet
		- uzytkownik : Uzytkownik
		- status : WypozycenieStatus
		+ Wypozycenie(Date, Date, Sprzet Uzytkownik)
		+ gettery() : ...
		- sprawdzStatus() : void
		+ wplac(double) : void
		+ wydaj() : void
		+ wezDoZaplaty() : double
	}

	class "Użytkownik" as UZY {
		- id : int
		- imie : String
		- nazwisko : String
		- dokument : String
		- email : String
		- haslo : String
		- nrTel : Optional<String>
		- adres : Optional<String>
		- blokada : Optional<Date>
		- wypozycenia : Set<Wypozycenie>
		- platnosci : Set<Platnosc>
		- wnioski : Set<Wniosek>
		+ sprawdzHaslo(String) : boolean
		+ zablokuj(Date) : void
		+ oplac(Wypozycenie, double) : void
		+ gettery(bez haslo)() : ...
		+ settery(bez Set<*> i id)(...) : void
		+ wypozyc(Date, Date, Sprzet) : void
		+ rezerwuj(Date, Date, Sprzet) : void
	}

	class "Platnosc" as PLA {
		- id : int
		- data : Date
		- wypozycenie : Wypozycenie
		- kwota : double
		+ Platnosc(Date, Wypozycenie, double)
		+ gettery() : ...
	}

	class "Wniosek" as WNI {
		- id : int
		- nowaData : Date
		- klient : Klient
		- wypozycenie : Wypozycenie
		- status : WniosekStatus
		+ rozpatrz(boolean) : void
		+ rozpatrz(Date) : void
		+ gettery() : ...
		+ Wniosek(Date, Klient, Wypozycenie)
	}

	class "Zlecenie" as ZLE {
		- id : int
		- status : ZlecenieStatus
		- sprzet : Sprzet
		+ Zlecenie(ZlecenieStatus, Sprzet)
		+ gettery() : ...
	}

	UPR -up-o BAD
	KAT -up-o BAD
	ETY -up-o BAD
	MAR -up-o BAD
	SPR -left-o BAD
	WYP -right-o BAD
	UZY -down-o BAD
	PLA -down-o BAD
	WNI -down-o BAD
	ZLE -down-o BAD
	
@enduml